workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      groups:
        - app_store_credentials
        - firebase_ios
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "ancientplustech.ancient.flip"
        # Environment variables - set these in Codemagic UI under Environment Variables
        # Required: ZEGO_APP_ID, ZEGO_APP_SIGN, AGORA_APP_ID, PAYSTACK_PUBLIC_KEY
        # Optional: ANCIENT_COIN_CLIENT_ID, ANCIENT_COIN_CLIENT_SECRET, ANCIENT_COIN_WALLET_ADDRESS
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > $CM_BUILD_DIR/flip/android/local.properties

      - name: Get Flutter packages
        script: |
          cd flip
          flutter packages pub get

      - name: Flutter analyze
        script: |
          cd flip
          flutter analyze || true

      - name: Debug - Check Flutter version
        script: |
          cd flip
          flutter --version
          flutter doctor -v

      - name: Create .env file
        script: |
          cd flip
          cat > .env << EOF
          ZEGO_APP_ID=${ZEGO_APP_ID}
          ZEGO_APP_SIGN=${ZEGO_APP_SIGN}
          AGORA_APP_ID=${AGORA_APP_ID}
          PAYSTACK_PUBLIC_KEY=${PAYSTACK_PUBLIC_KEY}
          ANCIENT_COIN_CLIENT_ID=${ANCIENT_COIN_CLIENT_ID:-}
          ANCIENT_COIN_CLIENT_SECRET=${ANCIENT_COIN_CLIENT_SECRET:-}
          ANCIENT_COIN_WALLET_ADDRESS=${ANCIENT_COIN_WALLET_ADDRESS:-}
          EOF
          echo "✅ Created .env file with environment variables"

      - name: Install CocoaPods dependencies
        script: |
          cd flip/ios
          pod repo update
          pod install
          cd ../..

      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: |
          keychain initialize

      - name: Fetch signing files
        script: |
          cd flip
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Set up signing certificate
        script: |
          keychain add-certificates

      - name: Set up code signing settings on Xcode project
        script: |
          cd flip
          xcode-project use-profiles

      - name: Debug - List schemes and workspace info
        script: |
          cd flip/ios
          echo "=== Available Schemes ==="
          xcodebuild -list -workspace Runner.xcworkspace
          echo "=== Workspace structure ==="
          ls -la Runner.xcworkspace/
          cd ../..

      - name: Debug - Check if Runner scheme exists
        script: |
          cd flip/ios
          xcodebuild -showBuildSettings -workspace Runner.xcworkspace -scheme Runner | head -20
          cd ../..

      - name: Build iOS app
        script: |
          cd flip
          BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID") + 1))
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist \
            --build-name=1.0.0 \
            --build-number=$BUILD_NUMBER

    artifacts:
      - flip/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flip/flutter_drive.log
      - flip/ios/Runner.xcworkspace/**/*

    publishing:
      email:
        recipients:
          - user@example.com  # Update with your email
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      flutter: stable
      android_sdk: "34.0.0"
      java: "17"
      groups:
        - keystore_credentials
        - firebase_android
      vars:
        PACKAGE_NAME: ancientplustech.ancient.flip
        # Environment variables - set these in Codemagic UI under Environment Variables
        # Required: ZEGO_APP_ID, ZEGO_APP_SIGN, AGORA_APP_ID, PAYSTACK_PUBLIC_KEY
        # Optional: ANCIENT_COIN_CLIENT_ID, ANCIENT_COIN_CLIENT_SECRET, ANCIENT_COIN_WALLET_ADDRESS
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > $CM_BUILD_DIR/flip/android/local.properties
      
      - name: Get Flutter dependencies
        script: |
          cd flip
          flutter pub get
      
      - name: Create .env file
        script: |
          cd flip
          cat > .env << EOF
          ZEGO_APP_ID=${ZEGO_APP_ID}
          ZEGO_APP_SIGN=${ZEGO_APP_SIGN}
          AGORA_APP_ID=${AGORA_APP_ID}
          PAYSTACK_PUBLIC_KEY=${PAYSTACK_PUBLIC_KEY}
          ANCIENT_COIN_CLIENT_ID=${ANCIENT_COIN_CLIENT_ID:-}
          ANCIENT_COIN_CLIENT_SECRET=${ANCIENT_COIN_CLIENT_SECRET:-}
          ANCIENT_COIN_WALLET_ADDRESS=${ANCIENT_COIN_WALLET_ADDRESS:-}
          EOF
          echo "✅ Created .env file with environment variables"
      
      - name: Flutter build appbundle
        script: |
          cd flip
          flutter build appbundle --release \
            --build-name=$(grep 'version:' pubspec.yaml | cut -d' ' -f2 | cut -d+ -f1) \
            --build-number=$(grep 'version:' pubspec.yaml | cut -d' ' -f2 | cut -d+ -f2)
    
    artifacts:
      - flip/build/app/outputs/bundle/**/*.aab
      - flip/build/app/outputs/flutter-apk/**/*.apk
    
    publishing:
      email:
        recipients:
          - user@example.com  # Update with your email
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal  # Options: internal, alpha, beta, production
        # submit_as_draft: true  # Uncomment to submit as draft

  # Combined workflow for both platforms
  build-all:
    name: Build iOS & Android
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      groups:
        - app_store_credentials
        - keystore_credentials
        - firebase_ios
        - firebase_android
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "ancientplustech.ancient.flip"
        PACKAGE_NAME: ancientplustech.ancient.flip
        # Environment variables - set these in Codemagic UI under Environment Variables
        # Required: ZEGO_APP_ID, ZEGO_APP_SIGN, AGORA_APP_ID, PAYSTACK_PUBLIC_KEY
        # Optional: ANCIENT_COIN_CLIENT_ID, ANCIENT_COIN_CLIENT_SECRET, ANCIENT_COIN_WALLET_ADDRESS
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > $CM_BUILD_DIR/flip/android/local.properties

      - name: Get Flutter packages
        script: |
          cd flip
          flutter packages pub get

      - name: Flutter analyze
        script: |
          cd flip
          flutter analyze || true

      - name: Create .env file
        script: |
          cd flip
          cat > .env << EOF
          ZEGO_APP_ID=${ZEGO_APP_ID}
          ZEGO_APP_SIGN=${ZEGO_APP_SIGN}
          AGORA_APP_ID=${AGORA_APP_ID}
          PAYSTACK_PUBLIC_KEY=${PAYSTACK_PUBLIC_KEY}
          ANCIENT_COIN_CLIENT_ID=${ANCIENT_COIN_CLIENT_ID:-}
          ANCIENT_COIN_CLIENT_SECRET=${ANCIENT_COIN_CLIENT_SECRET:-}
          ANCIENT_COIN_WALLET_ADDRESS=${ANCIENT_COIN_WALLET_ADDRESS:-}
          EOF
          echo "✅ Created .env file with environment variables"

      - name: Install CocoaPods dependencies
        script: |
          cd flip/ios
          pod repo update
          pod install
          cd ../..

      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: |
          keychain initialize

      - name: Fetch signing files
        script: |
          cd flip
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Set up signing certificate
        script: |
          keychain add-certificates

      - name: Set up code signing settings on Xcode project
        script: |
          cd flip
          xcode-project use-profiles

      - name: Build iOS app
        script: |
          cd flip
          BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID") + 1))
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist \
            --build-name=1.0.0 \
            --build-number=$BUILD_NUMBER

      - name: Flutter build appbundle
        script: |
          cd flip
          flutter build appbundle --release \
            --build-name=$(grep 'version:' pubspec.yaml | cut -d' ' -f2 | cut -d+ -f1) \
            --build-number=$(grep 'version:' pubspec.yaml | cut -d' ' -f2 | cut -d+ -f2)

    artifacts:
      - flip/build/ios/ipa/*.ipa
      - flip/build/app/outputs/bundle/**/*.aab
      - flip/build/app/outputs/flutter-apk/**/*.apk
      - /tmp/xcodebuild_logs/*.log
      - flip/flutter_drive.log
      - flip/ios/Runner.xcworkspace/**/*

    publishing:
      email:
        recipients:
          - user@example.com  # Update with your email
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal