workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      groups:
        - keys
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "ancientplustech.ancient.flip"
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Create .env file
        script: |
          echo "=== Creating .env file from environment variables ==="
          echo "ZEGO_APP_ID=${ZEGO_APP_ID}" > .env
          echo "ZEGO_APP_SIGN=${ZEGO_APP_SIGN}" >> .env
          echo "AGORA_APP_ID=${AGORA_APP_ID}" >> .env
          echo "API_URL=${API_URL}" >> .env
          echo "✅ .env file created successfully"

      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Flutter analyze
        script: |
          flutter analyze || true

      - name: Debug - Check Flutter version
        script: |
          flutter --version
          flutter doctor -v

      - name: Debug - List iOS files
        script: |
          ls -la ios/
          ls -la ios/Runner.xcodeproj/

      - name: Verify iOS permissions in Info.plist
        script: |
          echo "=== Checking iOS Permissions in Info.plist ==="
          if grep -q "NSCameraUsageDescription" ios/Runner/Info.plist; then
            echo "✅ NSCameraUsageDescription found"
            grep "NSCameraUsageDescription" ios/Runner/Info.plist
          else
            echo "❌ NSCameraUsageDescription NOT found"
          fi
          if grep -q "NSPhotoLibraryUsageDescription" ios/Runner/Info.plist; then
            echo "✅ NSPhotoLibraryUsageDescription found"
            grep "NSPhotoLibraryUsageDescription" ios/Runner/Info.plist
          else
            echo "❌ NSPhotoLibraryUsageDescription NOT found"
          fi
          if grep -q "NSPhotoLibraryAddUsageDescription" ios/Runner/Info.plist; then
            echo "✅ NSPhotoLibraryAddUsageDescription found"
            grep "NSPhotoLibraryAddUsageDescription" ios/Runner/Info.plist
          else
            echo "❌ NSPhotoLibraryAddUsageDescription NOT found"
          fi

          echo "=== Full Info.plist permissions section ==="
          grep -A 2 -B 1 "UsageDescription" ios/Runner/Info.plist || echo "No usage descriptions found"

      - name: Set up Firebase configuration
        script: |
          echo "=== Setting up Firebase configuration ==="
          if [ -n "$FIREBASE_OPTIONS_CONTENT" ]; then
            echo "$FIREBASE_OPTIONS_CONTENT" > lib/firebase_options.dart
            echo "✅ firebase_options.dart created successfully"
          else
            echo "⚠️ FIREBASE_OPTIONS_CONTENT not found in environment variables"
          fi

      - name: Set iOS deployment target
        script: |
          perl -i -pe 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Fix Pod deployment targets
        script: |
          echo "=== Fixing CocoaPods deployment targets ==="
          if ! grep -q "post_install do" ios/Podfile; then
            echo "" >> ios/Podfile
            echo "post_install do |installer|" >> ios/Podfile
            echo "  installer.pods_project.targets.each do |target|" >> ios/Podfile
            echo "    target.build_configurations.each do |config|" >> ios/Podfile
            echo "      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0" >> ios/Podfile
            echo "        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'" >> ios/Podfile
            echo "      end" >> ios/Podfile
            echo "    end" >> ios/Podfile
            echo "  end" >> ios/Podfile
            echo "end" >> ios/Podfile
            echo "✅ Added post_install hook to Podfile"
          else
            echo "✅ post_install hook already exists in Podfile"
          fi

      - name: Create and configure Settings.bundle
        script: |
          echo "=== Setting up Settings.bundle for iOS permissions ==="
          mkdir -p ios/Runner/Settings.bundle
          cat > ios/Runner/Settings.bundle/Root.plist << 'PLISTEOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
          	<key>StringsTable</key>
          	<string>Root</string>
          	<key>PreferenceSpecifiers</key>
          	<array>
          		<dict>
          			<key>Type</key>
          			<string>PSGroupSpecifier</string>
          			<key>Title</key>
          			<string>About Ancient Flip</string>
          		</dict>
          		<dict>
          			<key>Type</key>
          			<string>PSTitleValueSpecifier</string>
          			<key>Title</key>
          			<string>Version</string>
          			<key>Key</key>
          			<string>version</string>
          			<key>DefaultValue</key>
          			<string>1.0.0</string>
          		</dict>
          		<dict>
          			<key>Type</key>
          			<string>PSGroupSpecifier</string>
          			<key>Title</key>
          			<string>Privacy & Permissions</string>
          			<key>FooterText</key>
          			<string>Ancient Flip requires camera access and photo library access. You can manage these permissions in the main iOS Settings under Privacy > Camera and Privacy > Photos.</string>
          		</dict>
          		<dict>
          			<key>Type</key>
          			<string>PSGroupSpecifier</string>
          			<key>Title</key>
          			<string>Permission Reset Instructions</string>
          			<key>FooterText</key>
          			<string>If permissions are not working correctly, go to iOS Settings > General > Transfer or Reset iPhone > Reset > Reset Location & Privacy. This will reset all app permissions and allow apps to request them again.</string>
          		</dict>
          	</array>
          </dict>
          </plist>
          PLISTEOF
          echo "✅ Settings.bundle created"
          ls -la ios/Runner/Settings.bundle/
          if ! grep -q "Settings.bundle" ios/Runner.xcodeproj/project.pbxproj; then
            echo "⚠️ Adding Settings.bundle reference to Xcode project"
          else
            echo "✅ Settings.bundle already referenced in Xcode project"
          fi

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: |
          keychain initialize

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Set up signing certificate
        script: |
          keychain add-certificates

      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Debug - List schemes and workspace info
        script: |
          cd ios
          echo "=== Available Schemes ==="
          xcodebuild -list -workspace Runner.xcworkspace
          echo "=== Workspace structure ==="
          ls -la Runner.xcworkspace/
          cd ..

      - name: Debug - Check if Runner scheme exists
        script: |
          cd ios
          xcodebuild -showBuildSettings -workspace Runner.xcworkspace -scheme Runner | head -20
          cd ..

      - name: Build iOS app
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID") + 1))
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist \
            --build-name=1.0.0 \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      - ios/Runner.xcworkspace/**/*

    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID