// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK8dmD-I7gJKbyhRUyJojMDFfwv5T4clk',
    appId: '1:490623785866:web:1dcf1682efe65bebc58673',
    messagingSenderId: '490623785866',
    projectId: 'ancientflip-cee4f',
    authDomain: 'ancientflip-cee4f.firebaseapp.com',
    storageBucket: 'ancientflip-cee4f.firebasestorage.app',
    measurementId: 'G-B2ZC0HFT3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK_SKo75NpxxbnG3ZqhUjM7QFUZ6ytWQ8',
    appId: '1:490623785866:android:c6be34bf88eb1f06c58673',
    messagingSenderId: '490623785866',
    projectId: 'ancientflip-cee4f',
    storageBucket: 'ancientflip-cee4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhav_9c_RGyxiK5aM8vP71y59B0GuJUQc',
    appId: '1:490623785866:ios:bc2ba95f28b974e6c58673',
    messagingSenderId: '490623785866',
    projectId: 'ancientflip-cee4f',
    storageBucket: 'ancientflip-cee4f.firebasestorage.app',
    androidClientId:
        '490623785866-39822ejrst6q9putlkenb5ohb5aggm0f.apps.googleusercontent.com',
    iosClientId:
        '490623785866-sp0pe9tno2o8tusj5kosn4015m18s6j7.apps.googleusercontent.com',
    iosBundleId: 'ancientplustech.ancient.flip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhav_9c_RGyxiK5aM8vP71y59B0GuJUQc',
    appId: '1:490623785866:ios:bc2ba95f28b974e6c58673',
    messagingSenderId: '490623785866',
    projectId: 'ancientflip-cee4f',
    storageBucket: 'ancientflip-cee4f.firebasestorage.app',
    androidClientId:
        '490623785866-39822ejrst6q9putlkenb5ohb5aggm0f.apps.googleusercontent.com',
    iosClientId:
        '490623785866-sp0pe9tno2o8tusj5kosn4015m18s6j7.apps.googleusercontent.com',
    iosBundleId: 'ancientplustech.ancient.flip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK8dmD-I7gJKbyhRUyJojMDFfwv5T4clk',
    appId: '1:490623785866:web:b94552d343ff0ff9c58673',
    messagingSenderId: '490623785866',
    projectId: 'ancientflip-cee4f',
    authDomain: 'ancientflip-cee4f.firebaseapp.com',
    storageBucket: 'ancientflip-cee4f.firebasestorage.app',
    measurementId: 'G-LYQYGLV1HT',
  );
}
